apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: n9vg84ta7-java-quarkus
  janus-idp.io/tekton: n9vg84ta7-java-quarkus
  backstage.io/kubernetes-id: n9vg84ta7-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: n9vg84ta7-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
